#PBS -S /bin/bash
#PBS -l select=1:ncpus=28:model=bro
#PBS -l site=static_broadwell
#PBS -q devel
#PBS -l walltime=02:00:00
#PBS -j oe
#PBS -N EAP-MC
#PBS -o /nobackup/jakravit/git/EAP_parallel/job.log

# Working directory 
WDIR=/nobackup/jakravit/git/EAP_parallel/
cd $WDIR

#set environment
source /usr/share/modules/init/bash
module use -a /swbuild/analytix/tools/modulefiles
module load miniconda3/v4
source activate tf2_8

#run code
echo "Executing post runner on" `hostname` "in $PWD"
/swbuild/analytix/tools/miniconda3_220407/envs/tf2_9/bin/python EAP_cyano_vacuole.py
